import { NextResponse } from 'next/server';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

// Minimal GitHub API helper
async function ghFetch(url: string, options: RequestInit = {}) {
  const res = await fetch(`https://api.github.com${url}`, {
    ...options,
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
  return res;
}

export async function POST(req: Request) {
  try {
    if (!GITHUB_TOKEN) {
      return NextResponse.json(
        { error: 'GITHUB_TOKEN is missing in environment variables. Cannot sync to GitHub.' },
        { status: 400 }
      );
    }

    const { slug, htmlContent, projectName } = await req.json();
    if (!slug || !htmlContent) {
      return NextResponse.json({ error: 'Missing slug or htmlContent' }, { status: 400 });
    }

    const repoName = `tola-site-${slug}`;

    // 1. Get current Authenticated User to know the owner
    const userRes = await ghFetch('/user');
    if (!userRes.ok) throw new Error('Failed to parse GitHub Token user');
    const userData = await userRes.json();
    const owner = userData.login;

    // 2. Check if repo exists
    const repoRes = await ghFetch(`/repos/${owner}/${repoName}`);
    let repoExists = repoRes.ok;

    // 3. Create repo if not exists
    if (!repoExists) {
      const createRes = await ghFetch('/user/repos', {
        method: 'POST',
        body: JSON.stringify({
          name: repoName,
          description: `Landing Page generated by Tola SaaS for: ${projectName}`,
          private: false,
          auto_init: true
        })
      });
      if (!createRes.ok) throw new Error('Failed to create repository');
      
      // Wait a moment for GitHub to initialize it
      await new Promise(r => setTimeout(r, 2000));
    }

    // 4. Try to get the existing index.html SHA if it exists (for updating)
    let fileSha;
    const fileRes = await ghFetch(`/repos/${owner}/${repoName}/contents/index.html`);
    if (fileRes.ok) {
      const fileData = await fileRes.json();
      fileSha = fileData.sha;
    }

    // 5. Create or Update index.html
    const buffer = Buffer.from(htmlContent, 'utf-8');
    const base64Content = buffer.toString('base64');
    
    const updateRes = await ghFetch(`/repos/${owner}/${repoName}/contents/index.html`, {
      method: 'PUT',
      body: JSON.stringify({
        message: `Tola SaaS update: ${new Date().toLocaleString()}`,
        content: base64Content,
        sha: fileSha // Required if updating existing file
      })
    });

    if (!updateRes.ok) {
      const err = await updateRes.text();
      console.error("Github update error:", err);
      throw new Error('Failed to upload index.html');
    }

    return NextResponse.json({ success: true, repoUrl: `https://github.com/${owner}/${repoName}` });

  } catch (error: any) {
    console.error('Github Sync Error:', error.message);
    return NextResponse.json({ error: error.message || 'Internal error' }, { status: 500 });
  }
}
